### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [4GeeksAcademy/Domain-Generator-Raul-Gimenez#1]
Feedback de Sandra:

Muy buen trabajo Raúl! Todo funciona correctamente, solo noté que faltó agregar la extensión ".com, .net, etc". Con ese pequeño detalle, estaría perfectamente de 10!!!. ¡Ánimo, está es genial! Estoy ansiosa por ver más proyectos.

---

Feedback de Adrián:

Bien hecho! Pero revisa tu output para que cumpla las condiciones. Son dos cambios tontos, pero ten en cuenta lo que comenta Sandra y entrega el proyecto 100% terminado

**Comment by Raauul1996** [comment]
Gracias! Ya le he añadido, se me olvido ponerlo!!

**Comment by SandraMadarnas** [comment]
Feedback de Sandra: 

¡Buen trabajo, Raúl! Ahora sí, el proyecto está genial. Has hecho un trabajo excelente. Sigue así, porque vas por un camino excelente. ¡Continúa así con tu esfuerzo!
